name: Test Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test file
        run: echo "Hello, World!" > testfile.txt

      - name: Upload test file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-artifact
          path: testfile.txt
